---
title: "The Morality of Emotional-Wellbeing"
date: 2024-06-29T12:30:09-05:00
draft: true
---

Narratives take place all around us. They can occur in news publications when anchors and journalist establish a story about why inflation is high, but entertainment recommender systems rely on a given narrative to make suggestions to us. In previous decades, traditional radio hosts and DJs were more responsible for determining what a given population would listen to. We now know however, that there is more extensive corporate influence in the entirety of the music production process, from production to distribution, to audience listening habits. A remaining question, then, is what effects these realities portray. One potential answer involves narratives, with researchers of psychology and philosophy recognizing the ways in which narratives shape our self-identity and infuse our lives with meaning. As such, narratives can potentially constitute a key component of our own psychological development, meaning that corporate influence in the creation of mass narratives is an important topic for human wellbeing.

In my research, I consider the relationship between the emotional bonds among a community’s members and particular narratives central to those communities. I argue that narratives are crucial to culture, identity, and community, each of which are essential for well-being and as such, are a source of what I call moral knowledge. My research has two components. First, it explores the relationship between moral knowledge and popular narratives. Regarding this component, I am interested in all facets of public narrative, from popular music to the twenty-four-hour news cycle. The second component uses tools often used by data analysts, such as sentiment analysis (e.g., quanteda), it looks to deconstruct linguistic corpuses, and to contrast the emotional features of a given lyric corpus in response to moral kind terms in the expression of human relationships. Adopting a broadly sentimentalist moral perspective, I build upon the insights of narrative scholars like Eleonore Stump (2020), Martha Nussbaum, Mohamad Syed and Kate McLean, and other digital humanists like Marc Alfano. I propose an account where human well-being plays a vital role in questions of moral knowledge.
